server:
  port: 8851
spring:
  application:
    name: config-single-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: huest
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: config-client8851
management:
  endpoints:
    web:
      exposure:
        exclude: "*"