server:
  port: 8080
spring:
  application:
    name: uaa-service
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        exclude: refresh,health,info,env